/* Matlab R2020B only supports E2E Wrapper and does not support E2E Transformer used in BSW */
/* This file adapts the E2EPW interface generated by Simulink to the E2E Transformer interface provided by BSW */

#include "E2ePwToE2eXf.h"
#include "Rte_Type.h"

#if defined MATLAB_MEX_FILE || defined MODEL

/* EMPTY */

#else
static Rte_TransformerError TransformerError_01;
static Rte_TransformerError TransformerError_05;
Std_ReturnType E2EPW_ReadInit_SG_Zone_R_FAS_01_Group_SG_Zone_R_FAS_01_Group(void)
{
	return E_OK;
}

Rte_TransformerError TransformerError_01;
Rte_TransformerError TransformerError_05;
uint32 E2EPW_Read_SG_Zone_R_FAS_01_Group_SG_Zone_R_FAS_01_Group (SG_Zone_R_FAS_01_Group_Struct* data)
{
	//Rte_TransformerError TransformerError;
	/* Call Rte_Read function */
	(void) Rte_Read_SG_Zone_R_FAS_01_Group_SG_Zone_R_FAS_01_Group(data, &TransformerError_05);

	return (uint32)TransformerError_05.errorCode;
}

Std_ReturnType E2EPW_ReadInit_SG_Zone_R_FAS_02_Group_SG_Zone_R_FAS_02_Group(void)
{
	return E_OK;
}

uint32 E2EPW_Read_SG_Zone_R_FAS_02_Group_SG_Zone_R_FAS_02_Group (SG_Zone_R_FAS_02_Group_Struct* data)
{
	//Rte_TransformerError TransformerError;
	/* Call Rte_Read function */
	(void) Rte_Read_SG_Zone_R_FAS_02_Group_SG_Zone_R_FAS_02_Group(data, &TransformerError_01);

	return (uint32)TransformerError_01.errorCode;
}

#endif