/* Matlab R2020B only supports E2E Wrapper and does not support E2E Transformer used in BSW */
/* This file adapts the E2EPW interface generated by Simulink to the E2E Transformer interface provided by BSW */

#ifndef E2EPWTOE2EXF_H_
#define E2EPWTOE2EXF_H_

#if defined MATLAB_MEX_FILE || defined MODEL

/* EMPTY */

#else

#include "Rte_AsccSwc.h"

Std_ReturnType E2EPW_ReadInit_SG_Zone_R_FAS_01_Group_SG_Zone_R_FAS_01_Group(void);
uint32 E2EPW_Read_SG_Zone_R_FAS_01_Group_SG_Zone_R_FAS_01_Group (SG_Zone_R_FAS_01_Group_Struct* data);

Std_ReturnType E2EPW_ReadInit_SG_Zone_R_FAS_02_Group_SG_Zone_R_FAS_02_Group(void);
uint32 E2EPW_Read_SG_Zone_R_FAS_02_Group_SG_Zone_R_FAS_02_Group (SG_Zone_R_FAS_02_Group_Struct* data);

#endif

#endif
